add ore-distribute(app)

diff --git a/src/bin/artifact/ore-artifact b/src/bin/artifact/ore-artifact
--- a/src/bin/artifact/ore-artifact
+++ b/src/bin/artifact/ore-artifact
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 usage() {
-  echo "Usage: $(basename "$0") [-h] [-l] [-a] [artifact_name]"
+  echo "Usage: $(basename "$0") [-h] [-l] [-a] [artifact_name [version]]"
   echo "Get the path to the artifact."
   echo "  -h:  Show this help message"
   echo "without artifact_name:"
@@ -34,7 +34,7 @@ while getopts "hal" arg; do
 done
 shift $((OPTIND - 1))
 
-if [[ $# -ne 0 ]] && [[ $# -ne 1 ]]; then
+if [[ $# -ne 0 ]] && [[ $# -ne 1 ]] && [[ $# -ne 2 ]]; then
   usage
   exit 0
 fi
@@ -49,6 +49,12 @@ elif [[ $# -eq 1 ]]; then
     echo "Error: Cannot use both -a and -l options together."
     exit 1
   fi
+elif [[ $# -eq 2 ]]; then
+  if [[ $list_all == true || $list_latest == true ]]; then
+    echo "Error: Cannot use -a or -l options with specific version."
+    exit 1
+  fi
+
 fi
 
 readonly artifact_name=$1
@@ -65,4 +71,11 @@ elif [[ $# -eq 1 ]]; then
   else
     echo "$root/$artifact_name"
   fi
+
+elif [[ $# -eq 2 ]]; then
+  readonly version=$2
+  readonly versionTemplate="${version}"
+  grep_regex=${versionTemplate//\$\{version\}/$version}
+
+  find "$root/$artifact_name" -type f | grep "$grep_regex"
 fi
