ore-artifact (-c copy)

diff --git a/src/bin/artifact/ore-artifact b/src/bin/artifact/ore-artifact
--- a/src/bin/artifact/ore-artifact
+++ b/src/bin/artifact/ore-artifact
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 usage() {
-  echo "Usage: $(basename "$0") [-h] [-l] [-a] [artifact_name [version]]"
+  echo "Usage: $(basename "$0") [-h] [-l] [-a] [-c path] [artifact_name [version]]"
   echo "Get the path to the artifact."
   echo "  -h:  Show this help message"
   echo "without artifact_name:"
@@ -10,11 +10,15 @@ usage() {
   echo "       prints the root path of the artifact"
   echo "  -a:  List path to all versions of artifact"
   echo "  -l:  List path to latest version of artifact"
+  echo "with artifact_name and version given:"
+  echo "       prints the path to the specified version of the artifact"
+  echo "  -c:  copy the artifact to the specified path (uses with -l and version options)"
 }
 
 list_all=false
 list_latest=false
-while getopts "hal" arg; do
+copy_path=
+while getopts "halc:" arg; do
   case $arg in
   h)
     usage
@@ -25,6 +29,9 @@ while getopts "hal" arg; do
     ;;
   l)
     list_latest=true
+    ;;
+  c)
+    copy_path=$OPTARG
     ;;
   *)
     usage
@@ -54,7 +61,12 @@ elif [[ $# -eq 2 ]]; then
     echo "Error: Cannot use -a or -l options with specific version."
     exit 1
   fi
-
+fi
+if [[ -n $copy_path ]]; then
+  if [[ $# -ne 2 && $list_latest == false ]]; then
+    echo "Error: -c option must be used with artifact_name and version or -l option."
+    exit 1
+  fi
 fi
 
 readonly artifact_name=$1
@@ -67,7 +79,12 @@ elif [[ $# -eq 1 ]]; then
   if [[ $list_all == true ]]; then
     find "$root/$artifact_name" -type f | sort -V
   elif [[ $list_latest == true ]]; then
-    find "$root/$artifact_name" -type f | sort -V | tail -n 1
+    if [[ -z $copy_path ]]; then
+      find "$root/$artifact_name" -type f | sort -V | tail -n 1
+    else
+      latest_path=$(find "$root/$artifact_name" -type f | sort -V | tail -n 1)
+      cp -v "$latest_path" "$copy_path"
+    fi
   else
     echo "$root/$artifact_name"
   fi
@@ -77,5 +94,10 @@ elif [[ $# -eq 2 ]]; then
   readonly versionTemplate="${version}"
   grep_regex=${versionTemplate//\$\{version\}/$version}
 
-  find "$root/$artifact_name" -type f | grep "$grep_regex"
+  if [[ -z $copy_path ]]; then
+    find "$root/$artifact_name" -type f | grep "$grep_regex"
+  else
+    version_path=$(find "$root/$artifact_name" -type f | grep "$grep_regex")
+    cp -v "$version_path" "$copy_path"
+  fi
 fi
